version: '3.7'

services:
  app:
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/application:cached

  nginx:
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - ./public:/application/public:cached
      - ./storage/app/public/:/application/public/storage/:cached

  redis:
    ports:
      - 16379:6379

networks:
  default:
