version: '3.7'

services:
  app:
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/application:cached
    networks:
      - tcd


  nginx:
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./public:/application/public:cached
      - ./storage/app/public/:/application/public/storage/:cached
    networks:
      - tcd

  redis:
    ports:
      - 6379:6379
    networks:
      - tcd

networks:
  tcd:
