version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./_docker/app/Dockerfile
    restart: always
    networks:
      - tcd

  nginx:
    build:
      context: .
      dockerfile: ./_docker/nginx/Dockerfile
    depends_on:
      - app
    restart: always
    networks:
      - tcd

  redis:
    image: redis:alpine
    restart: always
    networks:
      - tcd

networks:
  tcd:
